<?php
namespace Ipsum\Reservation\database\seeds;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Ipsum\Reservation\app\Models\Reservation\Pays;

class PaysTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('pays')->truncate();
        foreach ($this->getDatas() as $data) {
            Pays::create($data);
        }

    }

    private function getDatas()
    {
        return array(
            array('id' => '1','code' => '4','alpha2' => 'AF','alpha3' => 'AFG','nom' => "Afghanistan",'callingCodes'=>'93'),
            array('id' => '2','code' => '8','alpha2' => 'AL','alpha3' => 'ALB','nom' => "Albanie",'callingCodes'=>'355'),
            array('id' => '3','code' => '10','alpha2' => 'AQ','alpha3' => 'ATA','nom' => "Antarctique",'callingCodes'=>'672'),
            array('id' => '4','code' => '12','alpha2' => 'DZ','alpha3' => 'DZA','nom' => "Algérie",'callingCodes'=>'213'),
            array('id' => '5','code' => '16','alpha2' => 'AS','alpha3' => 'ASM','nom' => "Samoa Américaines",'callingCodes'=>'1684'),
            array('id' => '6','code' => '20','alpha2' => 'AD','alpha3' => 'AND','nom' => "Andorre",'callingCodes'=>'376'),
            array('id' => '7','code' => '24','alpha2' => 'AO','alpha3' => 'AGO','nom' => "Angola",'callingCodes'=>'244'),
            array('id' => '8','code' => '28','alpha2' => 'AG','alpha3' => 'ATG','nom' => "Antigua-et-Barbuda",'callingCodes'=>'1268'),
            array('id' => '9','code' => '31','alpha2' => 'AZ','alpha3' => 'AZE','nom' => "Azerbaïdjan",'callingCodes'=>'994'),
            array('id' => '10','code' => '32','alpha2' => 'AR','alpha3' => 'ARG','nom' => "Argentine",'callingCodes'=>'54'),
            array('id' => '11','code' => '36','alpha2' => 'AU','alpha3' => 'AUS','nom' => "Australie",'callingCodes'=>'61'),
            array('id' => '12','code' => '40','alpha2' => 'AT','alpha3' => 'AUT','nom' => "Autriche",'callingCodes'=>'43'),
            array('id' => '13','code' => '44','alpha2' => 'BS','alpha3' => 'BHS','nom' => "Bahamas",'callingCodes'=>'1242'),
            array('id' => '14','code' => '48','alpha2' => 'BH','alpha3' => 'BHR','nom' => "Bahreïn",'callingCodes'=>'973'),
            array('id' => '15','code' => '50','alpha2' => 'BD','alpha3' => 'BGD','nom' => "Bangladesh",'callingCodes'=>'880'),
            array('id' => '16','code' => '51','alpha2' => 'AM','alpha3' => 'ARM','nom' => "Arménie",'callingCodes'=>'374'),
            array('id' => '17','code' => '52','alpha2' => 'BB','alpha3' => 'BRB','nom' => "Barbade",'callingCodes'=>'1246'),
            array('id' => '18','code' => '56','alpha2' => 'BE','alpha3' => 'BEL','nom' => "Belgique",'callingCodes'=>'32'),
            array('id' => '19','code' => '60','alpha2' => 'BM','alpha3' => 'BMU','nom' => "Bermudes",'callingCodes'=>'1441'),
            array('id' => '20','code' => '64','alpha2' => 'BT','alpha3' => 'BTN','nom' => "Bhoutan",'callingCodes'=>'975'),
            array('id' => '21','code' => '68','alpha2' => 'BO','alpha3' => 'BOL','nom' => "Bolivie",'callingCodes'=>'591'),
            array('id' => '22','code' => '70','alpha2' => 'BA','alpha3' => 'BIH','nom' => "Bosnie-Herzégovine",'callingCodes'=>'387'),
            array('id' => '23','code' => '72','alpha2' => 'BW','alpha3' => 'BWA','nom' => "Botswana",'callingCodes'=>'267'),
            array('id' => '24','code' => '74','alpha2' => 'BV','alpha3' => 'BVT','nom' => "Île Bouvet",'callingCodes'=>''),
            array('id' => '25','code' => '76','alpha2' => 'BR','alpha3' => 'BRA','nom' => "Brésil",'callingCodes'=>'55'),
            array('id' => '26','code' => '84','alpha2' => 'BZ','alpha3' => 'BLZ','nom' => "Belize",'callingCodes'=>'501'),
            array('id' => '27','code' => '86','alpha2' => 'IO','alpha3' => 'IOT','nom' => "Territoire Britannique de l'Océan Indien",'callingCodes'=>'246'),
            array('id' => '28','code' => '90','alpha2' => 'SB','alpha3' => 'SLB','nom' => "Îles Salomon",'callingCodes'=>'677'),
            array('id' => '29','code' => '92','alpha2' => 'VG','alpha3' => 'VGB','nom' => "Îles Vierges Britanniques",'callingCodes'=>'1284'),
            array('id' => '30','code' => '96','alpha2' => 'BN','alpha3' => 'BRN','nom' => "Brunéi Darussalam",'callingCodes'=>'673'),
            array('id' => '31','code' => '100','alpha2' => 'BG','alpha3' => 'BGR','nom' => "Bulgarie",'callingCodes'=>'359'),
            array('id' => '32','code' => '104','alpha2' => 'MM','alpha3' => 'MMR','nom' => "Myanmar",'callingCodes'=>'95'),
            array('id' => '33','code' => '108','alpha2' => 'BI','alpha3' => 'BDI','nom' => "Burundi",'callingCodes'=>'257'),
            array('id' => '34','code' => '112','alpha2' => 'BY','alpha3' => 'BLR','nom' => "Bélarus",'callingCodes'=>'375'),
            array('id' => '35','code' => '116','alpha2' => 'KH','alpha3' => 'KHM','nom' => "Cambodge",'callingCodes'=>'855'),
            array('id' => '36','code' => '120','alpha2' => 'CM','alpha3' => 'CMR','nom' => "Cameroun",'callingCodes'=>'237'),
            array('id' => '37','code' => '124','alpha2' => 'CA','alpha3' => 'CAN','nom' => "Canada",'callingCodes'=>'1'),
            array('id' => '38','code' => '132','alpha2' => 'CV','alpha3' => 'CPV','nom' => "Cap-vert",'callingCodes'=>'238'),
            array('id' => '39','code' => '136','alpha2' => 'KY','alpha3' => 'CYM','nom' => "Îles Caïmanes",'callingCodes'=>'1345'),
            array('id' => '40','code' => '140','alpha2' => 'CF','alpha3' => 'CAF','nom' => "République Centrafricaine",'callingCodes'=>'236'),
            array('id' => '41','code' => '144','alpha2' => 'LK','alpha3' => 'LKA','nom' => "Sri Lanka",'callingCodes'=>'94'),
            array('id' => '42','code' => '148','alpha2' => 'TD','alpha3' => 'TCD','nom' => "Tchad",'callingCodes'=>'235'),
            array('id' => '43','code' => '152','alpha2' => 'CL','alpha3' => 'CHL','nom' => "Chili",'callingCodes'=>'56'),
            array('id' => '44','code' => '156','alpha2' => 'CN','alpha3' => 'CHN','nom' => "Chine",'callingCodes'=>'86'),
            array('id' => '45','code' => '158','alpha2' => 'TW','alpha3' => 'TWN','nom' => "Taïwan",'callingCodes'=>'886'),
            array('id' => '46','code' => '162','alpha2' => 'CX','alpha3' => 'CXR','nom' => "Île Christmas",'callingCodes'=>'61'),
            array('id' => '47','code' => '166','alpha2' => 'CC','alpha3' => 'CCK','nom' => "Îles Cocos (Keeling)",'callingCodes'=>'61'),
            array('id' => '48','code' => '170','alpha2' => 'CO','alpha3' => 'COL','nom' => "Colombie",'callingCodes'=>'57'),
            array('id' => '49','code' => '174','alpha2' => 'KM','alpha3' => 'COM','nom' => "Comores",'callingCodes'=>'269'),
            array('id' => '50','code' => '175','alpha2' => 'YT','alpha3' => 'MYT','nom' => "Mayotte",'callingCodes'=>'262'),
            array('id' => '51','code' => '178','alpha2' => 'CG','alpha3' => 'COG','nom' => "République du Congo",'callingCodes'=>'242'),
            array('id' => '52','code' => '180','alpha2' => 'CD','alpha3' => 'COD','nom' => "République Démocratique du Congo",'callingCodes'=>'243'),
            array('id' => '53','code' => '184','alpha2' => 'CK','alpha3' => 'COK','nom' => "Îles Cook",'callingCodes'=>'682'),
            array('id' => '54','code' => '188','alpha2' => 'CR','alpha3' => 'CRI','nom' => "Costa Rica",'callingCodes'=>'506'),
            array('id' => '55','code' => '191','alpha2' => 'HR','alpha3' => 'HRV','nom' => "Croatie",'callingCodes'=>'385'),
            array('id' => '56','code' => '192','alpha2' => 'CU','alpha3' => 'CUB','nom' => "Cuba",'callingCodes'=>'53'),
            array('id' => '57','code' => '196','alpha2' => 'CY','alpha3' => 'CYP','nom' => "Chypre",'callingCodes'=>'357'),
            array('id' => '58','code' => '203','alpha2' => 'CZ','alpha3' => 'CZE','nom' => "République Tchèque",'callingCodes'=>'420'),
            array('id' => '59','code' => '204','alpha2' => 'BJ','alpha3' => 'BEN','nom' => "Bénin",'callingCodes'=>'229'),
            array('id' => '60','code' => '208','alpha2' => 'DK','alpha3' => 'DNK','nom' => "Danemark",'callingCodes'=>'45'),
            array('id' => '61','code' => '212','alpha2' => 'DM','alpha3' => 'DMA','nom' => "Dominique",'callingCodes'=>'1767'),
            array('id' => '62','code' => '214','alpha2' => 'DO','alpha3' => 'DOM','nom' => "République Dominicaine",'callingCodes'=>'1809,1829,1849'),
            array('id' => '63','code' => '218','alpha2' => 'EC','alpha3' => 'ECU','nom' => "Équateur",'callingCodes'=>'593'),
            array('id' => '64','code' => '222','alpha2' => 'SV','alpha3' => 'SLV','nom' => "El Salvador",'callingCodes'=>'503'),
            array('id' => '65','code' => '226','alpha2' => 'GQ','alpha3' => 'GNQ','nom' => "Guinée Équatoriale",'callingCodes'=>'240'),
            array('id' => '66','code' => '231','alpha2' => 'ET','alpha3' => 'ETH','nom' => "Éthiopie",'callingCodes'=>'251'),
            array('id' => '67','code' => '232','alpha2' => 'ER','alpha3' => 'ERI','nom' => "Érythrée",'callingCodes'=>'291'),
            array('id' => '68','code' => '233','alpha2' => 'EE','alpha3' => 'EST','nom' => "Estonie",'callingCodes'=>'372'),
            array('id' => '69','code' => '234','alpha2' => 'FO','alpha3' => 'FRO','nom' => "Îles Féroé",'callingCodes'=>'298'),
            array('id' => '70','code' => '238','alpha2' => 'FK','alpha3' => 'FLK','nom' => "Îles (malvinas) Falkland",'callingCodes'=>'500'),
            array('id' => '71','code' => '239','alpha2' => 'GS','alpha3' => 'SGS','nom' => "Géorgie du Sud et les Îles Sandwich du Sud",'callingCodes'=>'500'),
            array('id' => '72','code' => '242','alpha2' => 'FJ','alpha3' => 'FJI','nom' => "Fidji",'callingCodes'=>'679'),
            array('id' => '73','code' => '246','alpha2' => 'FI','alpha3' => 'FIN','nom' => "Finlande",'callingCodes'=>'358'),
            array('id' => '74','code' => '248','alpha2' => 'AX','alpha3' => 'ALA','nom' => "Îles Åland",'callingCodes'=>'358'),
            array('id' => '75','code' => '250','alpha2' => 'FR','alpha3' => 'FRA','nom' => "France métropolitaine",'callingCodes'=>'33'),
            array('id' => '76','code' => '254','alpha2' => 'GF','alpha3' => 'GUF','nom' => "Guyane Française",'callingCodes'=>'594'),
            array('id' => '77','code' => '258','alpha2' => 'PF','alpha3' => 'PYF','nom' => "Polynésie Française",'callingCodes'=>'689'),
            array('id' => '78','code' => '260','alpha2' => 'TF','alpha3' => 'ATF','nom' => "Terres Australes Françaises",'callingCodes'=>''),
            array('id' => '79','code' => '262','alpha2' => 'DJ','alpha3' => 'DJI','nom' => "Djibouti",'callingCodes'=>'253'),
            array('id' => '80','code' => '266','alpha2' => 'GA','alpha3' => 'GAB','nom' => "Gabon",'callingCodes'=>'241'),
            array('id' => '81','code' => '268','alpha2' => 'GE','alpha3' => 'GEO','nom' => "Géorgie",'callingCodes'=>'995'),
            array('id' => '82','code' => '270','alpha2' => 'GM','alpha3' => 'GMB','nom' => "Gambie",'callingCodes'=>'220'),
            array('id' => '83','code' => '275','alpha2' => 'PS','alpha3' => 'PSE','nom' => "Territoire Palestinien Occupé",'callingCodes'=>'970'),
            array('id' => '84','code' => '276','alpha2' => 'DE','alpha3' => 'DEU','nom' => "Allemagne",'callingCodes'=>'49'),
            array('id' => '85','code' => '288','alpha2' => 'GH','alpha3' => 'GHA','nom' => "Ghana",'callingCodes'=>'233'),
            array('id' => '86','code' => '292','alpha2' => 'GI','alpha3' => 'GIB','nom' => "Gibraltar",'callingCodes'=>'350'),
            array('id' => '87','code' => '296','alpha2' => 'KI','alpha3' => 'KIR','nom' => "Kiribati",'callingCodes'=>'686'),
            array('id' => '88','code' => '300','alpha2' => 'GR','alpha3' => 'GRC','nom' => "Grèce",'callingCodes'=>'30'),
            array('id' => '89','code' => '304','alpha2' => 'GL','alpha3' => 'GRL','nom' => "Groenland",'callingCodes'=>'299'),
            array('id' => '90','code' => '308','alpha2' => 'GD','alpha3' => 'GRD','nom' => "Grenade",'callingCodes'=>'1473'),
            array('id' => '91','code' => '312','alpha2' => 'GP','alpha3' => 'GLP','nom' => "Guadeloupe",'callingCodes'=>'590'),
            array('id' => '92','code' => '316','alpha2' => 'GU','alpha3' => 'GUM','nom' => "Guam",'callingCodes'=>'1671'),
            array('id' => '93','code' => '320','alpha2' => 'GT','alpha3' => 'GTM','nom' => "Guatemala",'callingCodes'=>'502'),
            array('id' => '94','code' => '324','alpha2' => 'GN','alpha3' => 'GIN','nom' => "Guinée",'callingCodes'=>'224'),
            array('id' => '95','code' => '328','alpha2' => 'GY','alpha3' => 'GUY','nom' => "Guyana",'callingCodes'=>'592'),
            array('id' => '96','code' => '332','alpha2' => 'HT','alpha3' => 'HTI','nom' => "Haïti",'callingCodes'=>'509'),
            array('id' => '97','code' => '334','alpha2' => 'HM','alpha3' => 'HMD','nom' => "Îles Heard et Mcdonald",'callingCodes'=>''),
            array('id' => '98','code' => '336','alpha2' => 'VA','alpha3' => 'VAT','nom' => "Saint-Siège (état de la Cité du Vatican)",'callingCodes'=>'379'),
            array('id' => '99','code' => '340','alpha2' => 'HN','alpha3' => 'HND','nom' => "Honduras",'callingCodes'=>'504'),
            array('id' => '100','code' => '344','alpha2' => 'HK','alpha3' => 'HKG','nom' => "Hong-Kong",'callingCodes'=>'852'),
            array('id' => '101','code' => '348','alpha2' => 'HU','alpha3' => 'HUN','nom' => "Hongrie",'callingCodes'=>'36'),
            array('id' => '102','code' => '352','alpha2' => 'IS','alpha3' => 'ISL','nom' => "Islande",'callingCodes'=>'354'),
            array('id' => '103','code' => '356','alpha2' => 'IN','alpha3' => 'IND','nom' => "Inde",'callingCodes'=>'91'),
            array('id' => '104','code' => '360','alpha2' => 'ID','alpha3' => 'IDN','nom' => "Indonésie",'callingCodes'=>'62'),
            array('id' => '105','code' => '364','alpha2' => 'IR','alpha3' => 'IRN','nom' => "République Islamique d'Iran",'callingCodes'=>'98'),
            array('id' => '106','code' => '368','alpha2' => 'IQ','alpha3' => 'IRQ','nom' => "Iraq",'callingCodes'=>'964'),
            array('id' => '107','code' => '372','alpha2' => 'IE','alpha3' => 'IRL','nom' => "Irlande",'callingCodes'=>'353'),
            array('id' => '108','code' => '376','alpha2' => 'IL','alpha3' => 'ISR','nom' => "Israël",'callingCodes'=>'972'),
            array('id' => '109','code' => '380','alpha2' => 'IT','alpha3' => 'ITA','nom' => "Italie",'callingCodes'=>'39'),
            array('id' => '110','code' => '384','alpha2' => 'CI','alpha3' => 'CIV','nom' => "Côte d'Ivoire",'callingCodes'=>'225'),
            array('id' => '111','code' => '388','alpha2' => 'JM','alpha3' => 'JAM','nom' => "Jamaïque",'callingCodes'=>'1876'),
            array('id' => '112','code' => '392','alpha2' => 'JP','alpha3' => 'JPN','nom' => "Japon",'callingCodes'=>'81'),
            array('id' => '113','code' => '398','alpha2' => 'KZ','alpha3' => 'KAZ','nom' => "Kazakhstan",'callingCodes'=>'76,77'),
            array('id' => '114','code' => '400','alpha2' => 'JO','alpha3' => 'JOR','nom' => "Jordanie",'callingCodes'=>'962'),
            array('id' => '115','code' => '404','alpha2' => 'KE','alpha3' => 'KEN','nom' => "Kenya",'callingCodes'=>'254'),
            array('id' => '116','code' => '408','alpha2' => 'KP','alpha3' => 'PRK','nom' => "République Populaire Démocratique de Corée",'callingCodes'=>'850'),
            array('id' => '117','code' => '410','alpha2' => 'KR','alpha3' => 'KOR','nom' => "République de Corée",'callingCodes'=>'82'),
            array('id' => '118','code' => '414','alpha2' => 'KW','alpha3' => 'KWT','nom' => "Koweït",'callingCodes'=>'965'),
            array('id' => '119','code' => '417','alpha2' => 'KG','alpha3' => 'KGZ','nom' => "Kirghizistan",'callingCodes'=>'996'),
            array('id' => '120','code' => '418','alpha2' => 'LA','alpha3' => 'LAO','nom' => "République Démocratique Populaire Lao",'callingCodes'=>'856'),
            array('id' => '121','code' => '422','alpha2' => 'LB','alpha3' => 'LBN','nom' => "Liban",'callingCodes'=>'961'),
            array('id' => '122','code' => '426','alpha2' => 'LS','alpha3' => 'LSO','nom' => "Lesotho",'callingCodes'=>'266'),
            array('id' => '123','code' => '428','alpha2' => 'LV','alpha3' => 'LVA','nom' => "Lettonie",'callingCodes'=>'371'),
            array('id' => '124','code' => '430','alpha2' => 'LR','alpha3' => 'LBR','nom' => "Libéria",'callingCodes'=>'231'),
            array('id' => '125','code' => '434','alpha2' => 'LY','alpha3' => 'LBY','nom' => "Jamahiriya Arabe Libyenne",'callingCodes'=>'218'),
            array('id' => '126','code' => '438','alpha2' => 'LI','alpha3' => 'LIE','nom' => "Liechtenstein",'callingCodes'=>'423'),
            array('id' => '127','code' => '440','alpha2' => 'LT','alpha3' => 'LTU','nom' => "Lituanie",'callingCodes'=>'370'),
            array('id' => '128','code' => '442','alpha2' => 'LU','alpha3' => 'LUX','nom' => "Luxembourg",'callingCodes'=>'352'),
            array('id' => '129','code' => '446','alpha2' => 'MO','alpha3' => 'MAC','nom' => "Macao",'callingCodes'=>'853'),
            array('id' => '130','code' => '450','alpha2' => 'MG','alpha3' => 'MDG','nom' => "Madagascar",'callingCodes'=>'261'),
            array('id' => '131','code' => '454','alpha2' => 'MW','alpha3' => 'MWI','nom' => "Malawi",'callingCodes'=>'265'),
            array('id' => '132','code' => '458','alpha2' => 'MY','alpha3' => 'MYS','nom' => "Malaisie",'callingCodes'=>'60'),
            array('id' => '133','code' => '462','alpha2' => 'MV','alpha3' => 'MDV','nom' => "Maldives",'callingCodes'=>'960'),
            array('id' => '134','code' => '466','alpha2' => 'ML','alpha3' => 'MLI','nom' => "Mali",'callingCodes'=>'223'),
            array('id' => '135','code' => '470','alpha2' => 'MT','alpha3' => 'MLT','nom' => "Malte",'callingCodes'=>'356'),
            array('id' => '136','code' => '474','alpha2' => 'MQ','alpha3' => 'MTQ','nom' => "Martinique",'callingCodes'=>'596'),
            array('id' => '137','code' => '478','alpha2' => 'MR','alpha3' => 'MRT','nom' => "Mauritanie",'callingCodes'=>'222'),
            array('id' => '138','code' => '480','alpha2' => 'MU','alpha3' => 'MUS','nom' => "Maurice",'callingCodes'=>'230'),
            array('id' => '139','code' => '484','alpha2' => 'MX','alpha3' => 'MEX','nom' => "Mexique",'callingCodes'=>'52'),
            array('id' => '140','code' => '492','alpha2' => 'MC','alpha3' => 'MCO','nom' => "Monaco",'callingCodes'=>'377'),
            array('id' => '141','code' => '496','alpha2' => 'MN','alpha3' => 'MNG','nom' => "Mongolie",'callingCodes'=>'976'),
            array('id' => '142','code' => '498','alpha2' => 'MD','alpha3' => 'MDA','nom' => "République de Moldova",'callingCodes'=>'373'),
            array('id' => '143','code' => '500','alpha2' => 'MS','alpha3' => 'MSR','nom' => "Montserrat",'callingCodes'=>'1664'),
            array('id' => '144','code' => '504','alpha2' => 'MA','alpha3' => 'MAR','nom' => "Maroc",'callingCodes'=>'212'),
            array('id' => '145','code' => '508','alpha2' => 'MZ','alpha3' => 'MOZ','nom' => "Mozambique",'callingCodes'=>'258'),
            array('id' => '146','code' => '512','alpha2' => 'OM','alpha3' => 'OMN','nom' => "Oman",'callingCodes'=>'968'),
            array('id' => '147','code' => '516','alpha2' => 'NA','alpha3' => 'NAM','nom' => "Namibie",'callingCodes'=>'264'),
            array('id' => '148','code' => '520','alpha2' => 'NR','alpha3' => 'NRU','nom' => "Nauru",'callingCodes'=>'674'),
            array('id' => '149','code' => '524','alpha2' => 'NP','alpha3' => 'NPL','nom' => "Népal",'callingCodes'=>'977'),
            array('id' => '150','code' => '528','alpha2' => 'NL','alpha3' => 'NLD','nom' => "Pays-Bas",'callingCodes'=>'31'),
            array('id' => '151','code' => '530','alpha2' => 'AN','alpha3' => 'ANT','nom' => "Antilles Néerlandaises",'callingCodes'=>''),
            array('id' => '152','code' => '533','alpha2' => 'AW','alpha3' => 'ABW','nom' => "Aruba",'callingCodes'=>'297'),
            array('id' => '153','code' => '540','alpha2' => 'NC','alpha3' => 'NCL','nom' => "Nouvelle-Calédonie",'callingCodes'=>'687'),
            array('id' => '154','code' => '548','alpha2' => 'VU','alpha3' => 'VUT','nom' => "Vanuatu",'callingCodes'=>'678'),
            array('id' => '155','code' => '554','alpha2' => 'NZ','alpha3' => 'NZL','nom' => "Nouvelle-Zélande",'callingCodes'=>'64'),
            array('id' => '156','code' => '558','alpha2' => 'NI','alpha3' => 'NIC','nom' => "Nicaragua",'callingCodes'=>'505'),
            array('id' => '157','code' => '562','alpha2' => 'NE','alpha3' => 'NER','nom' => "Niger",'callingCodes'=>'227'),
            array('id' => '158','code' => '566','alpha2' => 'NG','alpha3' => 'NGA','nom' => "Nigéria",'callingCodes'=>'234'),
            array('id' => '159','code' => '570','alpha2' => 'NU','alpha3' => 'NIU','nom' => "Niué",'callingCodes'=>'683'),
            array('id' => '160','code' => '574','alpha2' => 'NF','alpha3' => 'NFK','nom' => "Île Norfolk",'callingCodes'=>'672'),
            array('id' => '161','code' => '578','alpha2' => 'NO','alpha3' => 'NOR','nom' => "Norvège",'callingCodes'=>'47'),
            array('id' => '162','code' => '580','alpha2' => 'MP','alpha3' => 'MNP','nom' => "Îles Mariannes du Nord",'callingCodes'=>'1670'),
            array('id' => '163','code' => '581','alpha2' => 'UM','alpha3' => 'UMI','nom' => "Îles Mineures Éloignées des États-Unis",'callingCodes'=>''),
            array('id' => '164','code' => '583','alpha2' => 'FM','alpha3' => 'FSM','nom' => "États Fédérés de Micronésie",'callingCodes'=>'691'),
            array('id' => '165','code' => '584','alpha2' => 'MH','alpha3' => 'MHL','nom' => "Îles Marshall",'callingCodes'=>'692'),
            array('id' => '166','code' => '585','alpha2' => 'PW','alpha3' => 'PLW','nom' => "Palaos",'callingCodes'=>'680'),
            array('id' => '167','code' => '586','alpha2' => 'PK','alpha3' => 'PAK','nom' => "Pakistan",'callingCodes'=>'92'),
            array('id' => '168','code' => '591','alpha2' => 'PA','alpha3' => 'PAN','nom' => "Panama",'callingCodes'=>'507'),
            array('id' => '169','code' => '598','alpha2' => 'PG','alpha3' => 'PNG','nom' => "Papouasie-Nouvelle-Guinée",'callingCodes'=>'675'),
            array('id' => '170','code' => '600','alpha2' => 'PY','alpha3' => 'PRY','nom' => "Paraguay",'callingCodes'=>'595'),
            array('id' => '171','code' => '604','alpha2' => 'PE','alpha3' => 'PER','nom' => "Pérou",'callingCodes'=>'51'),
            array('id' => '172','code' => '608','alpha2' => 'PH','alpha3' => 'PHL','nom' => "Philippines",'callingCodes'=>'63'),
            array('id' => '173','code' => '612','alpha2' => 'PN','alpha3' => 'PCN','nom' => "Pitcairn",'callingCodes'=>'64'),
            array('id' => '174','code' => '616','alpha2' => 'PL','alpha3' => 'POL','nom' => "Pologne",'callingCodes'=>'48'),
            array('id' => '175','code' => '620','alpha2' => 'PT','alpha3' => 'PRT','nom' => "Portugal",'callingCodes'=>'351'),
            array('id' => '176','code' => '624','alpha2' => 'GW','alpha3' => 'GNB','nom' => "Guinée-Bissau",'callingCodes'=>'245'),
            array('id' => '177','code' => '626','alpha2' => 'TL','alpha3' => 'TLS','nom' => "Timor-Leste",'callingCodes'=>'670'),
            array('id' => '178','code' => '630','alpha2' => 'PR','alpha3' => 'PRI','nom' => "Porto Rico",'callingCodes'=>'1787,1939'),
            array('id' => '179','code' => '634','alpha2' => 'QA','alpha3' => 'QAT','nom' => "Qatar",'callingCodes'=>'974'),
            array('id' => '180','code' => '638','alpha2' => 'RE','alpha3' => 'REU','nom' => "Réunion",'callingCodes'=>'262'),
            array('id' => '181','code' => '642','alpha2' => 'RO','alpha3' => 'ROU','nom' => "Roumanie",'callingCodes'=>'40'),
            array('id' => '182','code' => '643','alpha2' => 'RU','alpha3' => 'RUS','nom' => "Fédération de Russie",'callingCodes'=>'7'),
            array('id' => '183','code' => '646','alpha2' => 'RW','alpha3' => 'RWA','nom' => "Rwanda",'callingCodes'=>'250'),
            array('id' => '184','code' => '654','alpha2' => 'SH','alpha3' => 'SHN','nom' => "Sainte-Hélène",'callingCodes'=>'290'),
            array('id' => '185','code' => '659','alpha2' => 'KN','alpha3' => 'KNA','nom' => "Saint-Kitts-et-Nevis",'callingCodes'=>'1869'),
            array('id' => '186','code' => '660','alpha2' => 'AI','alpha3' => 'AIA','nom' => "Anguilla",'callingCodes'=>'1264'),
            array('id' => '187','code' => '662','alpha2' => 'LC','alpha3' => 'LCA','nom' => "Sainte-Lucie",'callingCodes'=>'1758'),
            array('id' => '188','code' => '666','alpha2' => 'PM','alpha3' => 'SPM','nom' => "Saint-Pierre-et-Miquelon",'callingCodes'=>'508'),
            array('id' => '189','code' => '670','alpha2' => 'VC','alpha3' => 'VCT','nom' => "Saint-Vincent-et-les Grenadines",'callingCodes'=>'1784'),
            array('id' => '190','code' => '674','alpha2' => 'SM','alpha3' => 'SMR','nom' => "Saint-Marin",'callingCodes'=>'378'),
            array('id' => '191','code' => '678','alpha2' => 'ST','alpha3' => 'STP','nom' => "Sao Tomé-et-Principe",'callingCodes'=>'239'),
            array('id' => '192','code' => '682','alpha2' => 'SA','alpha3' => 'SAU','nom' => "Arabie Saoudite",'callingCodes'=>'966'),
            array('id' => '193','code' => '686','alpha2' => 'SN','alpha3' => 'SEN','nom' => "Sénégal",'callingCodes'=>'221'),
            array('id' => '194','code' => '690','alpha2' => 'SC','alpha3' => 'SYC','nom' => "Seychelles",'callingCodes'=>'248'),
            array('id' => '195','code' => '694','alpha2' => 'SL','alpha3' => 'SLE','nom' => "Sierra Leone",'callingCodes'=>'232'),
            array('id' => '196','code' => '702','alpha2' => 'SG','alpha3' => 'SGP','nom' => "Singapour",'callingCodes'=>'65'),
            array('id' => '197','code' => '703','alpha2' => 'SK','alpha3' => 'SVK','nom' => "Slovaquie",'callingCodes'=>'421'),
            array('id' => '198','code' => '704','alpha2' => 'VN','alpha3' => 'VNM','nom' => "Viet Nam",'callingCodes'=>'84'),
            array('id' => '199','code' => '705','alpha2' => 'SI','alpha3' => 'SVN','nom' => "Slovénie",'callingCodes'=>'386'),
            array('id' => '200','code' => '706','alpha2' => 'SO','alpha3' => 'SOM','nom' => "Somalie",'callingCodes'=>'252'),
            array('id' => '201','code' => '710','alpha2' => 'ZA','alpha3' => 'ZAF','nom' => "Afrique du Sud",'callingCodes'=>'27'),
            array('id' => '202','code' => '716','alpha2' => 'ZW','alpha3' => 'ZWE','nom' => "Zimbabwe",'callingCodes'=>'263'),
            array('id' => '203','code' => '724','alpha2' => 'ES','alpha3' => 'ESP','nom' => "Espagne",'callingCodes'=>'34'),
            array('id' => '204','code' => '732','alpha2' => 'EH','alpha3' => 'ESH','nom' => "Sahara Occidental",'callingCodes'=>'212'),
            array('id' => '205','code' => '736','alpha2' => 'SD','alpha3' => 'SDN','nom' => "Soudan",'callingCodes'=>'249'),
            array('id' => '206','code' => '740','alpha2' => 'SR','alpha3' => 'SUR','nom' => "Suriname",'callingCodes'=>'597'),
            array('id' => '207','code' => '744','alpha2' => 'SJ','alpha3' => 'SJM','nom' => "Svalbard etÎle Jan Mayen",'callingCodes'=>'4779'),
            array('id' => '208','code' => '748','alpha2' => 'SZ','alpha3' => 'SWZ','nom' => "Swaziland",'callingCodes'=>'268'),
            array('id' => '209','code' => '752','alpha2' => 'SE','alpha3' => 'SWE','nom' => "Suède",'callingCodes'=>'46'),
            array('id' => '210','code' => '756','alpha2' => 'CH','alpha3' => 'CHE','nom' => "Suisse",'callingCodes'=>'41'),
            array('id' => '211','code' => '760','alpha2' => 'SY','alpha3' => 'SYR','nom' => "République Arabe Syrienne",'callingCodes'=>'963'),
            array('id' => '212','code' => '762','alpha2' => 'TJ','alpha3' => 'TJK','nom' => "Tadjikistan",'callingCodes'=>'992'),
            array('id' => '213','code' => '764','alpha2' => 'TH','alpha3' => 'THA','nom' => "Thaïlande",'callingCodes'=>'66'),
            array('id' => '214','code' => '768','alpha2' => 'TG','alpha3' => 'TGO','nom' => "Togo",'callingCodes'=>'228'),
            array('id' => '215','code' => '772','alpha2' => 'TK','alpha3' => 'TKL','nom' => "Tokelau",'callingCodes'=>'690'),
            array('id' => '216','code' => '776','alpha2' => 'TO','alpha3' => 'TON','nom' => "Tonga",'callingCodes'=>'676'),
            array('id' => '217','code' => '780','alpha2' => 'TT','alpha3' => 'TTO','nom' => "Trinité-et-Tobago",'callingCodes'=>'1868'),
            array('id' => '218','code' => '784','alpha2' => 'AE','alpha3' => 'ARE','nom' => "Émirats Arabes Unis",'callingCodes'=>'971'),
            array('id' => '219','code' => '788','alpha2' => 'TN','alpha3' => 'TUN','nom' => "Tunisie",'callingCodes'=>'216'),
            array('id' => '220','code' => '792','alpha2' => 'TR','alpha3' => 'TUR','nom' => "Turquie",'callingCodes'=>'90'),
            array('id' => '221','code' => '795','alpha2' => 'TM','alpha3' => 'TKM','nom' => "Turkménistan",'callingCodes'=>'993'),
            array('id' => '222','code' => '796','alpha2' => 'TC','alpha3' => 'TCA','nom' => "Îles Turks et Caïques",'callingCodes'=>'1649'),
            array('id' => '223','code' => '798','alpha2' => 'TV','alpha3' => 'TUV','nom' => "Tuvalu",'callingCodes'=>'688'),
            array('id' => '224','code' => '800','alpha2' => 'UG','alpha3' => 'UGA','nom' => "Ouganda",'callingCodes'=>'256'),
            array('id' => '225','code' => '804','alpha2' => 'UA','alpha3' => 'UKR','nom' => "Ukraine",'callingCodes'=>'380'),
            array('id' => '226','code' => '807','alpha2' => 'MK','alpha3' => 'MKD','nom' => "L'ex-République Yougoslave de Macédoine",'callingCodes'=>'389'),
            array('id' => '227','code' => '818','alpha2' => 'EG','alpha3' => 'EGY','nom' => "Égypte",'callingCodes'=>'20'),
            array('id' => '228','code' => '826','alpha2' => 'GB','alpha3' => 'GBR','nom' => "Royaume-Uni",'callingCodes'=>'44'),
            array('id' => '229','code' => '833','alpha2' => 'IM','alpha3' => 'IMN','nom' => "Île de Man",'callingCodes'=>'44'),
            array('id' => '230','code' => '834','alpha2' => 'TZ','alpha3' => 'TZA','nom' => "République-Unie de Tanzanie",'callingCodes'=>'255'),
            array('id' => '231','code' => '840','alpha2' => 'US','alpha3' => 'USA','nom' => "États-Unis",'callingCodes'=>'1'),
            array('id' => '232','code' => '850','alpha2' => 'VI','alpha3' => 'VIR','nom' => "Îles Vierges des États-Unis",'callingCodes'=>'1 340'),
            array('id' => '233','code' => '854','alpha2' => 'BF','alpha3' => 'BFA','nom' => "Burkina Faso",'callingCodes'=>'226'),
            array('id' => '234','code' => '858','alpha2' => 'UY','alpha3' => 'URY','nom' => "Uruguay",'callingCodes'=>'598'),
            array('id' => '235','code' => '860','alpha2' => 'UZ','alpha3' => 'UZB','nom' => "Ouzbékistan",'callingCodes'=>'998'),
            array('id' => '236','code' => '862','alpha2' => 'VE','alpha3' => 'VEN','nom' => "Venezuela",'callingCodes'=>'58'),
            array('id' => '237','code' => '876','alpha2' => 'WF','alpha3' => 'WLF','nom' => "Wallis et Futuna",'callingCodes'=>'681'),
            array('id' => '238','code' => '882','alpha2' => 'WS','alpha3' => 'WSM','nom' => "Samoa",'callingCodes'=>'685'),
            array('id' => '239','code' => '887','alpha2' => 'YE','alpha3' => 'YEM','nom' => "Yémen",'callingCodes'=>'967'),
            array('id' => '240','code' => '891','alpha2' => 'CS','alpha3' => 'SCG','nom' => "Serbie-et-Monténégro",'callingCodes'=>''),
            array('id' => '241','code' => '894','alpha2' => 'ZM','alpha3' => 'ZMB','nom' => "Zambie",'callingCodes'=>'260'),
            array('id' => '242','code' => '535','alpha2' => 'BQ','alpha3' => 'BES','nom' => "Bonaire, Saint-Eustache et Saba",'callingCodes'=>'5997'),
            array('id' => '243','code' => '531','alpha2' => 'CW','alpha3' => 'CUW','nom' => "Curaçao",'callingCodes'=>'599'),
            array('id' => '244','code' => '831','alpha2' => 'GG','alpha3' => 'GGY','nom' => "Guernesey",'callingCodes'=>'44'),
            array('id' => '245','code' => '832','alpha2' => 'JE','alpha3' => 'JEY','nom' => "Jersey",'callingCodes'=>'44'),
            array('id' => '246','code' => '499','alpha2' => 'ME','alpha3' => 'MNE','nom' => "Monténégro",'callingCodes'=>'382'),
            array('id' => '247','code' => '652','alpha2' => 'BL','alpha3' => 'BLM','nom' => "Saint-Barthélemy",'callingCodes'=>'590'),
            array('id' => '248','code' => '663','alpha2' => 'MF','alpha3' => 'MAF','nom' => "Saint-Martin",'callingCodes'=>'590'),
            array('id' => '249','code' => '688','alpha2' => 'RS','alpha3' => 'SRB','nom' => "Serbie",'callingCodes'=>'381'),
            array('id' => '250','code' => '534','alpha2' => 'SX','alpha3' => 'SXM','nom' => "Saint Martin (partie néerlandaise)",'callingCodes'=>'1721'),
            array('id' => '251','code' => '728','alpha2' => 'SS','alpha3' => 'SSD','nom' => "Soudan du Sud",'callingCodes'=>'211'),
        );
    }
}
